//
//  MainInteractor.swift
//  PryanikyTest
//
//  Created by Игорь Дикань on 04.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func fetchData()
}

protocol MainDataStore: class {
    //var name: String { get set }
}

final class MainInteractor {
    
    // MARK: - External vars
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    //var name: String = ""
    
    // MARK: - Internal vars
    private let dataService: DataService
    
    init(service: NetworkServiceable) {
        dataService = DataService(service: service)
    }
    
}

// MARK: - Business logic
extension MainInteractor: MainBusinessLogic {
    
    func fetchData() {
        let request = ListDataRequest()
        dataService.fetchListData(request) { [weak self] (result) in
            switch result {
            case .success(let response):
                self?.presenter?.present(response)
            case .failure(let error):
                print(error)
            }
        }
        let _ = ListDataResponse(data: [
                                    InormationItem(name: "hz",
                                                   data: DataItem(text: Optional("Текстовый блок"),
                                                                  url: nil,
                                                                  selectedId: nil,
                                                                  variants: nil)),
                                    InormationItem(name: "picture",
                                                   data: DataItem(text: Optional("Пряники"),
                                                                  url: Optional("https://pryaniky.com/static/img/logo-a-512.png"),
                                                                  selectedId: nil,
                                                                  variants: nil)),
                                    InormationItem(name: "selector",
                                                   data: DataItem(text: nil,
                                                                  url: nil,
                                                                  selectedId: Optional(1),
                                                                  variants: Optional([Variant(id: 1,
                                                                                              text: "Вариант раз"),
                                                                                      Variant(id: 2,
                                                                                              text: "Вариант два"),
                                                                                      Variant(id: 3,
                                                                                              text: "Вариант три")])))],
                                 view: ["hz", "selector", "picture", "hz"])
    }
}

// MARK: - Data store
extension MainInteractor: MainDataStore {
    
}
